
- name: Ensures  ssh dir exists
  file: path=/home/cumulus/.ssh state=directory mode=0700 owner=cumulus group=cumulus

- name: copy private keys
  copy: src=id_rsa dest=/home/cumulus/.ssh/id_rsa mode=0600 owner=cumulus group=cumulus
